services:
  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: rag-postgres
    restart: always
    environment:
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpassword
      POSTGRES_DB: ragdb

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:

